language: java
jdk:
- openjdk6
script: mvn clean package --settings settings.xml
after_success:
- mvn clean deploy -DskipTests --settings settings.xml
before_install:
- openssl aes-256-cbc -K $encrypted_40774fb95ca7_key -iv $encrypted_40774fb95ca7_iv
  -in key.asc.enc -out key.asc -d && gpg --fast-import key.asc
cache:
  directories:
    - ~/.m2/repository