language: java
jdk:
- openjdk6
cache:
  directories:
    - ~/.m2/repository
script: 
- mvn clean package
after_success:
- openssl aes-256-cbc -K $encrypted_40774fb95ca7_key -iv $encrypted_40774fb95ca7_iv -in key.asc.enc -out key.asc -d && gpg --fast-import key.asc
- mvn clean deploy -DskipTests --settings settings.xml -Pdeploy